#!/usr/bin/env python3
"""Generate Android vector drawables for the Font Awesome icons used by the Web UI.

The Web chat loads a self-hosted Font Awesome Free subset
(`static/vendor/icons/fa-subset.css`, built by `scripts/build_icon_subset.py`).
This script reads the icon names from that subset, downloads the matching
official SVGs for the same Font Awesome version and writes
`android/app/src/main/res/drawable/fa_<style>_<web_name>.xml`.

Drawables keep the Web class name (for example `fa-cog` -> `fa_solid_cog`) so
Compose code can mirror the Web markup directly.

Usage:
    python3 android/ci/sync-web-icons.py          # regenerate drawables
    python3 android/ci/sync-web-icons.py --check  # fail if drawables are stale
"""
from __future__ import annotations

import argparse
import json
import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SUBSET_CSS = ROOT / "static" / "vendor" / "icons" / "fa-subset.css"
OUT_DIR = ROOT / "android" / "app" / "src" / "main" / "res" / "drawable"

FA_VERSION = "6.5.2"
FA_CSS_URL = f"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/{FA_VERSION}/css/all.min.css"
FA_TREE_URL = f"https://api.github.com/repos/FortAwesome/Font-Awesome/git/trees/{FA_VERSION}?recursive=1"
FA_SVG_URL = f"https://raw.githubusercontent.com/FortAwesome/Font-Awesome/{FA_VERSION}/svgs/{{style}}/{{name}}.svg"
STYLES = ("solid", "regular", "brands")
ICON_HEIGHT_DP = 24

SELECTOR_ICON_RE = re.compile(r"\.fa-([a-z0-9-]+):before")
CONTENT_RULE_RE = re.compile(r"""([^{}]+)\{content:"(\\[0-9a-fA-F]+)"\}""")
VIEWBOX_RE = re.compile(r'viewBox="0 0 ([0-9.]+) ([0-9.]+)"')
PATH_RE = re.compile(r'<path d="([^"]+)"')


def fetch(url: str) -> str:
    request = urllib.request.Request(url, headers={"User-Agent": "ai-playground-icon-sync"})
    with urllib.request.urlopen(request, timeout=60) as response:
        return response.read().decode("utf-8")


def used_icon_names() -> list[str]:
    css = SUBSET_CSS.read_text(encoding="utf-8")
    return sorted(set(SELECTOR_ICON_RE.findall(css)))


def alias_groups(css: str) -> dict[str, list[str]]:
    """Map every icon name to all names sharing its glyph (Font Awesome aliases)."""
    by_code: dict[str, list[str]] = {}
    for selectors, code in CONTENT_RULE_RE.findall(css):
        names = SELECTOR_ICON_RE.findall(selectors)
        if names:
            by_code.setdefault(code.lower(), []).extend(names)
    groups: dict[str, list[str]] = {}
    for names in by_code.values():
        for name in names:
            groups[name] = names
    return groups


def available_svgs() -> set[str]:
    tree = json.loads(fetch(FA_TREE_URL))
    if tree.get("truncated"):
        raise SystemExit("GitHub tree listing was truncated; cannot resolve SVG names")
    return {item["path"] for item in tree["tree"] if item["path"].startswith("svgs/")}


def drawable_xml(style: str, web_name: str, svg_name: str, svg: str) -> str:
    viewbox = VIEWBOX_RE.search(svg)
    path = PATH_RE.search(svg)
    if not viewbox or not path:
        raise SystemExit(f"unexpected SVG format: {style}/{svg_name}")
    width, height = float(viewbox.group(1)), float(viewbox.group(2))
    width_dp = round(ICON_HEIGHT_DP * width / height, 3)
    alias = "" if svg_name == web_name else f" (Web class fa-{web_name})"
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        f"<!-- Font Awesome Free {FA_VERSION} {style}/{svg_name}{alias}. "
        "Icon license: CC BY 4.0 https://fontawesome.com/license/free\n"
        "     Generated by android/ci/sync-web-icons.py; do not edit by hand. -->\n"
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        f'    android:width="{width_dp:g}dp"\n'
        f'    android:height="{ICON_HEIGHT_DP}dp"\n'
        f'    android:viewportWidth="{width:g}"\n'
        f'    android:viewportHeight="{height:g}">\n'
        f'    <path\n        android:fillColor="#FF000000"\n        android:pathData="{path.group(1)}" />\n'
        "</vector>\n"
    )


def build() -> dict[str, str]:
    groups = alias_groups(fetch(FA_CSS_URL))
    svgs = available_svgs()
    outputs: dict[str, str] = {}
    missing: list[str] = []
    for web_name in used_icon_names():
        candidates = [web_name] + [n for n in groups.get(web_name, []) if n != web_name]
        found = False
        for style in STYLES:
            svg_name = next((n for n in candidates if f"svgs/{style}/{n}.svg" in svgs), None)
            if svg_name is None:
                continue
            svg = fetch(FA_SVG_URL.format(style=style, name=svg_name))
            file_name = f"fa_{style}_{web_name.replace('-', '_')}.xml"
            outputs[file_name] = drawable_xml(style, web_name, svg_name, svg)
            found = True
        if not found:
            missing.append(web_name)
    # Utility classes (fa-spin, fa-fw, ...) and Pro-only names have no SVG; they are expected to be missing.
    if missing:
        print("no Free SVG (utility or unknown class): " + ", ".join(missing), file=sys.stderr)
    return outputs


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="only verify that drawables are up to date")
    args = parser.parse_args()
    outputs = build()
    existing = {p.name: p for p in OUT_DIR.glob("fa_*.xml")}
    stale = sorted(set(existing) - set(outputs))
    changed = sorted(n for n, text in outputs.items()
                     if n not in existing or existing[n].read_text(encoding="utf-8") != text)
    if args.check:
        if stale or changed:
            print("icon drawables are out of date: " + ", ".join(stale + changed), file=sys.stderr)
            return 1
        print(f"ok: {len(outputs)} icon drawables are up to date")
        return 0
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for name in stale:
        existing[name].unlink()
    for name in changed:
        (OUT_DIR / name).write_text(outputs[name], encoding="utf-8")
    print(f"wrote {len(changed)} and removed {len(stale)} of {len(outputs)} icon drawables")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
